### ISSUE TITLE
Using Cucumber 7 adapter with TestNG shows gives wrong number of tests in Report

### ISSUE THREAD

**Issue by Soumendu-Khilar** [grasshopper7/extentreports-cucumber7-adapter#20]
Hi,

I have a Cucumber-TestNG-Maven-Java project in which I used cucumber7 adapter to generate the extent reports. The number of Scenarios that the report is capturing is 1 more than the actual number of scenarios.

This is my Runner file setup.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/84026163/206370502-bb4236c7-2b93-42df-baca-9b42d755e59a.png">

This is the Feature file.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/84026163/206370753-a686a734-4c2e-4c5f-bf59-ee0a33df4604.png">

Cucumber Version: 7.2.3
TestNG Version: 7.4.0
Cucumber Adapter Version: 1.7.0

Below is the report. As can be seen report has captured the Scenario Outline twice although the run is Once.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/84026163/206371261-a5686632-9abb-4366-97c1-389595666595.png">

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/84026163/206371379-dfc058fa-cbd3-4254-a7d3-6d5c4e4307f4.png">

**Comment by grasshopper7** [comment]
Use the latest version in maven - 1.9.2. This will fix the issue in the tag details. 
The test page displays the feature, scenario outline, scenario, step hierarchy.  The scenario outline name is reused for the scenario name by default. To differentiate between these have a look at this example feature file - https://github.com/grasshopper7/cuke7-extent-adapter-report/blob/ac7c232d01bcc6a60b01507cb0affbaa9caf708e/cuke7-extent-adapter-report/src/test/resources/stepdefs/scenario%26outline.feature#L8

**Comment by amar212b** [comment]
have the same problem when using tags for a cucumber - junit gradle project .I am using the latest version but still seeing the issue. @grasshopper7

**Comment by grasshopper7** [comment]
Are you referring to the tags issue - plus 1 for scenario outline? What version? Gradle or maven should not make any difference.
Plz add a screenshot. thx

**Comment by amar212b** [comment]
Hi @grasshopper7 -unfortunately working on office project ,adding screenshot might be difficult but the issue is similar as mentioned above in the screenshot.
Suppose i have a scenario and i put 2 tags @a @b on it.
Now , in runner file i pass only @a in tags and run it ,the output html/pdf report shows 2 passed TC - one with @a and another with @b while only @ is run .
Plus in html report the passed percentage is shown as 0%.

Will try to provide screenshots by setting up project in my personal machine ,till then i hope i was able to provide some information

**Comment by grasshopper7** [comment]
Cucumber tag filtering for scenarios is based on the criterion that the tag is present for that scenario. It is like 'contains' rather than 'only has'. The report will output the data that it receives from cucumber and not perform any automatic filtering.

For the 0 pass percentage I will need more details of the feature files.

**Comment by amar212b** [comment]
![image](https://user-images.githubusercontent.com/61265892/226215414-891ebd4d-2f55-4eee-b1b1-4b2f83badbe3.png)
so this behavior is like this since both tags are present in cucumber.json which is although weird since im running only tag1 in runner.
![image](https://user-images.githubusercontent.com/61265892/226215481-10deeeaf-6682-41b2-9370-c89157fc8d19.png).
![image](https://user-images.githubusercontent.com/61265892/226215561-c7fddf1e-620d-4b83-acd5-441441027281.png)


for 0 percentage i could not replicate it in my local machine .not sure what is happening in the work project and why the behaviour is like that

**Comment by grasshopper7** [comment]
The behavior of the tag filtering by cucumber is reflected correctly in the report.
